### PR TITLE
cleanup: update github.com/rabbitmq/amqp091-go from 1.3.0 to 1.8.1

### PR DESCRIPTION
**Pull request by k4leung4**
# Changes

- 🧹 cleanup: update github.com/rabbitmq/amqp091-go from 1.3.0 to 1.8.1

1.3.0 was released on jan 13, 2022
1.8.1 was released on may 4, 2023

/kind cleanup

Fixes #

**Release Note**

```release-note
cleanup: update github.com/rabbitmq/amqp091-go from 1.3.0 to 1.8.1
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by gabo1208** [comment]
just the style error and it's good to go!

**Comment by k4leung4** [comment]
> just the style error and it's good to go!

thanks, the style is all in the vendor path, which i cant modify
not sure why it is not ignoring those files

**Review by gabo1208 — APPROVED** [review]

**Comment by gabo1208** [comment]
/override "Code Style / style / suggester / shell"

**Pull request merged**
