### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by vaikas**
# Update deps, the automation kept on failing so did it manually.

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by n3wscott** [comment]
hmmm

**Comment by vaikas** [comment]
This caused at least some of the problems:
https://github.com/knative-sandbox/eventing-rabbitmq/blob/master/.github/workflows/kind-e2e.yaml#L29

https://github.com/knative-sandbox/eventing-rabbitmq/pull/186/commits/25995c8652404d3eee71b2f81b8d0e0e47ee2e5b

**Comment by vaikas** [comment]
Rabbitmqcluster did not become ready, with new moar debugs it's:
```
=== RUN   TestSmokeBroker/Requirement/RabbitMQCluster_goes_ready
2021/01/08 12:06:05 rekt-hgnmeezm/rabbitmqc condition AllReplicasReady is not ready, NotAllPodsReady: 0/1 Pods ready
2021/01/08 12:10:25 Conditions for non-ready RabbitMQCluster rekt-kyhngmdk/rabbitmqc:
2021/01/08 12:10:25 rekt-kyhngmdk/rabbitmqc condition AllReplicasReady is: False  NotAllPodsReady: 0/1 Pods ready
2021/01/08 12:10:25 rekt-kyhngmdk/rabbitmqc condition ClusterAvailable is: False  NoEndpointsAvailable: The service has no endpoints available
2021/01/08 12:10:25 rekt-kyhngmdk/rabbitmqc condition NoWarnings is: True  NoWarnings: 
2021/01/08 12:10:25 rekt-kyhngmdk/rabbitmqc condition ReconcileSuccess is: True  Success: Created or Updated all child resources
```

**Comment by vaikas** [comment]
After splitting the tests into smaller chunks, most things pass. Source now fails with this unhelpful log message:

```
=== CONT  TestSourceDirect/Assert#01/[Alpha/MUST]RabbitMQ_source_goes_ready
=== CONT  TestSourceDirect/Assert#01/[Alpha/MUST]RabbitMQ_source_Delivers_events
2021/01/08 13:08:16 rabbitmq-source is not Deployed, DeploymentUnavailable: The Deployment 'rabbitmqsource-rabbitmq-source-8bade0855906fd95152c0f674e4fbd7f' is unavailable.
=== CONT  TestSourceDirect/Assert#01/[Alpha/MUST]RabbitMQ_source_goes_ready
    smoke_test_broker_trigger.go:57: all resources ready
```

**Pull request merged**
