### PR TITLE
fix for #8 Cannot build `master` branch

### LINKED ISSUE #8: Cannot build `master` branch
```
➜  eventing-rabbitmq git:(master) go build ./...
go: finding module for package github.com/cloudevents/sdk-go/v1/cloudevents/transport/http
go: finding module for package github.com/cloudevents/sdk-go/v1/cloudevents/client
go: finding module for package github.com/cloudevents/sdk-go/v1
../../go/pkg/mod/knative.dev/eventing@v0.14.2/pkg/utils/context.go:25:2: module github.com/cloudevents/sdk-go@latest found (v1.2.0), but does not contain package github.com/cloudevents/sdk-go/v1
../../go/pkg/mod/knative.dev/eventing@v0.14.2/pkg/utils/context.go:26:2: module github.com/cloudevents/sdk-go@latest found (v1.2.0), but does not contain package github.com/cloudevents/sdk-go/v1/cloudevents/transport/http
../../go/pkg/mod/knative.dev/eventing@v0.14.2/pkg/kncloudevents/good_client.go:23:2: module github.com/cloudevents/sdk-go@latest found (v1.2.0), but does not contain package github.com/cloudevents/sdk-go/v1/cloudevents/client
```

### PR DESCRIPTION
**Pull request by sbcd90**
closes #8

### CODE REVIEW

**Comment by sbcd90** [comment]
@vaikas please review as well.

**Comment by vaikas** [comment]
@sbcd90 my apologies, was on vacation. Tried to run the tests, and because it's set up to have prow run the jobs currently, your PR is failing. I have put a super hack until we add the tests to appease prow. I'll also start adding the github actions.
#10

**Comment by vaikas** [comment]
https://github.com/knative/test-infra/pull/2403

**Pull request merged**
