### PR TITLE
Fix tests env in Eventing RabbitMQ

### PR DESCRIPTION
**Pull request by gabo1208**
# Changes
- Reversed conformance test splitting
- Fixed unit test messages change

# Context
Right now, our unit tests are failing on Knative Eventing: 
image
For a change on some error messages. That's fixed here.
The CI been green depends now depends on the Knative eventing conformance tests to start passing test features to test feature sets as a reference, let's wait for that to happen

### CODE REVIEW

**Review by gab-satchi — COMMENTED** [review]
/lgtm

we can wait for eventing core to merge their changes

**Review by ChunyiLyu — APPROVED** [review]
LGTM

**Pull request merged**
