### PR TITLE
Trigger Subscriber Ref Namespace bug fix

### LINKED ISSUE #1117: Trigger unable to get subscriber uri across namespaces
**Describe the bug**
When a trigger/broker is in namespace A, it can not get the subscriber information for namespace B in order to forward events.

 **Expected behavior**
Trigger should be able to exist in namespace A and reference a service in namespace B

 **To Reproduce**
1) create namespaces "a" and "b"
2) create a broker in namespace "a"
3) create a service in namespace "b"
4) create a trigger in namespace "a" that references the broker in namespace a and references the subscriber in namespace "b"

 **Knative release version**
1.9.1

 **Additional context**
I already identified the location of the error. [Here](https://github.com/knative-sandbox/eventing-rabbitmq/blob/release-1.9/pkg/reconciler/trigger/trigger.go#L275) you will see that the subscriber ref namespace is overwritten to the namespace of the trigger without first checking if the namespace is empty. I am planning submit a pr to fix this myself, but wanted to document the issue for reference.

### PR DESCRIPTION
**Pull request by erictg**
# Changes

- :bug: Fix bug causing trigger subscriber ref namespace to be overwritten if provided

/kind bug

Fixes #1117

### CODE REVIEW

**Comment by erictg** [comment]
I will get back to this once I check with my company on CLA stuff

**Comment by erictg** [comment]
My CLA is signed

**Comment by erictg** [comment]
@gabo1208 I can push those tests in the next day or so, can you point me to where this e2e test should go?

**Comment by gabo1208** [comment]
Sure @erictg, here are the ones related to the broker and trigger https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/test/e2e/broker_test.go

**Comment by gabo1208** [comment]
@erictg Let me know if you need any help with this :)

Also for the CLA, you clicked the authorize button from the bot comment? I think you need that for it to authorize

**Comment by erictg** [comment]
Apologies for the delay in updating this pr, I added a unit test to validate the change I made. I'm not sure where/how I would update the integration test. 

Also, I signed the EasyCLA from that link and authorized it with CNCF. So it should be authorized. I had to do it via corporate contributor since the fork came form my companies github organization.

**Review by gabo1208 — APPROVED** [review]

**Comment by gabo1208** [comment]
No problem at all @erictg! I think it looks fine and it's ready to be merged :)

Buut you need to change the email from that commits to the one registered into the EasyCLA registration, is that possible? if not we can open a ticket with them and see what they say

**Comment by gabo1208** [comment]
cc @dprotaso @pierDipi @kvmware not sure what to do with the CLA here

**Comment by dprotaso** [comment]
Unsure what's up @lance how do we debug easycla issues?

**Comment by lance** [comment]
> Unsure what's up @lance how do we debug easycla issues?

Hey @dprotaso I'm traveling now and can't debug it myself. I would double check that the commits are associated with the same email used for easycla. If they do align and it's still not working maybe ask in the #easycla channel on the cncf slack.

**Comment by erictg** [comment]
Yeah that's fine with me, next time I'll fork from my personal account :)

**Pull request closed without merging**
