### PR TITLE
Update performance benchmarks post 1.0.0 release

### LINKED ISSUE #412: How can I benchmark eventing-rabbitmq?
Blocked on #239

## Ask
Instructions to setup and validate requirements listed under #239 - `Expectation from Developer perspective` given 
- a fresh K8s cluster > 1.21.0
- KUBECONFIG pointing to cluster

## References
Eventing - https://github.com/knative/eventing/tree/main/test/performance
Kafka - https://github.com/knative-sandbox/eventing-kafka/tree/main/test/performance

### PR DESCRIPTION
**Pull request by gvmw**
# Changes

- :broom: Update performance benchmark

/kind cleanup

Closes #412 for good. This is a follow-up to https://github.com/knative-sandbox/eventing-rabbitmq/pull/445.

I have confirmed that everything works as expected. I have removed all "smart" scripting and went with the plain approach. I have also included the results of the benchmarks in this repository, rather than referencing files that were uploaded as a GitHub thread comment.

There are a few unexpected behaviours here which I have captured in the README. Expanding on them below:

In previous iterations we didn't have any Receiver throughput values to plot. I am not sure why, but I have confirmed that we now have them.

When plotting throughput, especially receiver throughput, gnuplot can now take up to 5 minutes to load the graph. I suspect that this is due to the solid area which gets rendered. We never had it before, so this is a new & unexpected behaviour.

Screenshot 2021-11-04 at 13 00 25

When publishing 1k messages per second, the receiver cannot keep up. Increasing the CPU count from 1 to 2 doesn't help. I have attached a screenshot in the PR which captures the expected performance. We may want to troubleshoot, but for now we should just acknowledge that the 1k msg/s performance test may work for short bursts, but the workload is unsustainable (producers are constantly outpacing consumers).

Screenshot 2021-11-04 at 13 17 50

By the way, this 1k msg/s benchmark will take a really long time to complete (didn't wait), because the receiver consumes 3.4 msg/s 🤨

image

Lastly, I have confirmed that https://github.com/knative-sandbox/eventing-rabbitmq/issues/334#issuecomment-942411656 is spot-on from the broker perspective. Without it, the producer never waits for the broker and simply keeps pushing messages, like UDP does (fire & forget).

### CODE REVIEW

**Comment by gabo1208** [comment]
I'll wait for @xtreme-sameer-vohra and @benmoss to see this for the merge

**Comment by xtreme-sameer-vohra** [comment]
> By the way, this 1k msg/s benchmark will take a really long time to complete (didn't wait), because the receiver consumes 3.4 msg/s 🤨

The results between the 2 benchmarks original(135K in 3 mins) vs 1K Sustained(300K in 5 mins) seem **very** different 🤔 based on graphs. What am I missing ?

**Comment by gvmw** [comment]
> The results between the 2 benchmarks original(135K in 3 mins) vs 1K Sustained(300K in 5 mins) seem very different 🤔  based on graphs. What am I missing ?

The original benchmark is 500..1000 msg/s for 30 seconds in steps of 100, so 500 - 600 - 700 - 800 - 900 - 1000.

The last benchmark is 1000 msg/s sustained for 300 seconds, which is a struggle because the message backlog keeps growing and everything slows down to a crawl (3.5 msg/s).

Do the new instructions work for you @xtreme-sameer-vohra? I think that's what we care about in the context of this PR. Yes, we should look into the 1000 msg/s scenario, but as a separate PR / issue I think 🙂

**Pull request merged**
