### PR TITLE
Remove internal exchange and exclusive queue config from rabbitmqsource

### PR DESCRIPTION
**Pull request by ChunyiLyu**
# Changes

- :broom: internal exchange are usually created by the rmq server; exclusive queues get deleted when the declared connection closed. These configuration doesn't make sense for rabbitmqsource.
- :broom: also remove `nowait` configuration from exchangeConfig and queueConfig. 
- Fields are removed from CRD and docs.

/kind cleanup

Related to #581

### CODE REVIEW

**Review by gab-satchi — APPROVED** [review]
/lgtm

**Comment by ChunyiLyu** [comment]
@gab-satchi Why hold?

**Comment by gab-satchi** [comment]
@ChunyiLyu I just do hold so we can try and get 2 reviewers on the PR. Since your PRs get auto approved

**Review by gabo1208 — APPROVED** [review]

**Pull request merged**
