### PR TITLE
increase conformance test suite timeout to 1h

### PR DESCRIPTION
**Pull request by gab-satchi**

### CODE REVIEW

**Comment by gabo1208** [comment]
Reran e2e tests because of a flake

**Comment by gabo1208** [comment]
Retesting due to conformance flake, e2e are now ok

**Comment by kvmware** [comment]
Someone needs to work on these flakes lol :p

**Comment by gabo1208** [comment]
Hope is not me... xD jk

**Review by gabo1208 — APPROVED** [review]

**Pull request merged**
